Created skeleton of future application.
ElenaBelyasnik/javarush-project-1 pull request #1
Opened 2022-03-14 13:20 UTC by ElenaBelyasnik

Вы классные ребята. Мы будем стараться изо всех сил.

2022-03-17 22:16 UTC, AndryLat requested changes

2022-03-17 22:16 UTC, AndryLat commented on src/java/BrutForce.java
> +            e.printStackTrace();
мы с Антоном акцентировали на этом внимание. Тут лучше выводить сообщение с деталями в поток System.err хотя бы. И не тут, а в классе, который отвечает за общение с пользователем. Завтра я захочу переиспользовать твой метод для вебсервиса и у меня не будет возможности это сделать - у тебя результат работы выводится в консоль и я его никак не получу. А вот если бы метод возвращал результат своей работи дальше я мог бы с ним сделать все что угодно, то тогда все было бы корректно. Также тут лучше бросать эксепшн выше и ловить его так, где ты можешь его обработать.

2022-03-17 22:16 UTC, AndryLat commented on src/java/BrutForce.java
> +            if (s.contains(" и ")) {
А если вдруг в readingStrings окажется null значение? тогда все упадет с NPE. А чтобы этого избежать, я акцентировал внимание на подходе таком: "someText".equals(...)

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +    public static void menu() throws FileNotFoundException {
имя метода должно отображать действие. например, showMenu()

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +            System.out.println("5. Для выхода из приложения введите 5");
Можно вынести в отдельный метод или создать строковую константу.

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +                x = Integer.parseInt(s);
О чем говорит имя x ? я бы никогда не догадался, что это прееменная, которая хранит номер команды, введенный пользователем. Назови commandKey, userInput или как-то так.

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +            try {
Можно вынести в отдельный метод, который вернет тру или фолс.

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +                    System.out.println("Шифрование:");
Каждый кейз можно вынести в отдельный метод. Иначе твой свитч разрастется до немыслимых размеров. А если где-то потеряем break - будет вообще беда для будущих разработчиков. Именно поэтому я не рекомендую использовать свитч вообще, а использовать if-else или последние версии свитча, которые без брик.

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +                case 1:
1 - это магическое число. Если тебе пришлют кусок кода такой:
`switch (x) { case 1:` - ты догадаешься что тут происходит? не думаю. А если `switch(commandKey) { case ENCRYPT_COMMAND: ` будет понятнее?

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +    public static void inputParam1() {
а) имя метода не содержит дейтсвия. б) почему 1 ?

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
Почему не сканнер? проще же

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
буфферед ридер для чтения из консоли хорош только когда у нас ожидают громадные объемы входных данных.

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +            EncryptFile.key = Integer.parseInt(reader.readLine());
никогда так не делай. В реальных приложениях за такое расстрел.

Все, что находится в классе - должно быть в классе. Идеально если так: мы вызвали метод, передали туда данные, получили результат из метода и дальше показываем его либо пользователю, либо отправляем через веб сервис, либо как душе будет угодно. Если параметров много - создается объект, туда пишем все данные и передаем объект. 

так, как сделала ты - делает код сильносвязным, трудно понимаемым и при малейшем изменении ты задеваешь очень много мест и вероятность бага очень высока.

Алгоритм такой : считываешь все нужные значения, передаешь их в метод, получаешь из него результат, показываешь результат пользователю на основе того, что вернул метод.

2022-03-17 22:16 UTC, AndryLat commented on src/java/Dialogue.java
> +            System.out.println(e.getMessage());
если из наших мтеодов вылетел эксепшен, пишем это в System.err поток.

2022-03-17 22:16 UTC, AndryLat commented on src/java/EncryptFile.java
> +                encrAlphabet[i] = ALPHABET[delta];
encr - я бы если не знал контекста приложения, я бы не догадался что это значит.

2022-03-18 15:35 UTC, ElenaBelyasnik commented on src/java/Dialogue.java
> +            System.out.println("5. Для выхода из приложения введите 5");
Не поняла... Что вынести в отдельный метод?

2022-03-18 15:35 UTC, ElenaBelyasnik commented on src/java/Dialogue.java
> +            try {
Тоже не поняла, что надо вынести в отдельный метод?

2022-03-23 19:21 UTC, merged

2022-03-29 11:05 UTC, AndryLat commented on src/java/EncryptFile.java
> +    private static void setEncrAlphabet(int key) {
сначала лучше публичные методы, потом приватные. От публичной бизнес логики к сугубо техническим приватным методам.

А также вопрос: что такое encr?

2022-03-29 11:05 UTC, AndryLat commented on src/java/EncryptFile.java
> +    public static void start(int k, String origFile, String encryptFile) {
Кт отакой k? кто такой orig?

2022-03-29 11:05 UTC, AndryLat commented on src/java/EncryptFile.java
> +                String line = reader.readLine().toLowerCase().replace('ё', 'е');
Дискриминация:)

2022-03-29 11:05 UTC, AndryLat commented on src/java/EncryptFile.java
> +                        chars[i] = '#';
Кт отакой '#' ?

2022-03-29 11:05 UTC, AndryLat commented on src/java/KeyDecodingFile.java
> +    private static List<String> list = new ArrayList<>();
О чем говорит имя переменной?

2022-03-29 11:05 UTC, AndryLat commented on src/java/KeyDecodingFile.java
> +        setEncryptAlphabet();
состояние плохо тем, что если ты забудешь вызвать этот метод - будет беда, а почему - надо будет еще разобраться.

2022-03-29 11:05 UTC, AndryLat commented on src/java/KeyDecodingFile.java
> +            for (String s : list) {
for (String s : list) если я тебе скину этот кусок, ты никогда не догадаешься, что тут происходит, даже если это твой код:)

2022-03-29 11:05 UTC, AndryLat commented on src/java/Main.java
> +}
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-03-29 11:05 UTC, AndryLat commented on src/java/Main.java
> +            System.err.println(e.getMessage());
однотипная обработка, можно использовать |

2022-03-29 11:05 UTC, AndryLat commented on src/java/StatisticalAnalysis.java
> +            if (code == code1) {
if (code == code1) -> грустный смайлик